devtools::install_version("ggplot2", "2.2.0")
devtools::install_version("mosaic", "0.14.4")
devtools::install_version("HSAUR", "1.3-8")
devtools::install_version("MASS", "7.3-47")
devtools::install_version("mosaicData", "0.14.0")
devtools::install_version("openintro", "1.4")
